## Authentication

## Roles

- `administrator`
- `manager`
- `roles`

## Permissions

- `view_establishment`
- `create_establishment`
- `edit_establishment`
- `delete_establishment`
- `view_establishment_token`
- `create_establishment_token`
- `edit_establishment_token`
- `delete_establishment_token`
- `view_accommodation`
- `create_accommodation`
- `edit_accommodation`
- `delete_accommodation`
- `view_rental`
- `create_rental`
- `edit_rental`
- `delete_rental`
- `view_client`
- `create_client`
- `edit_client`
- `delete_client`
- `view_booking`
- `create_booking`
- `edit_booking`
- `delete_booking`
- `view_payment`
- `create_payment`
- `edit_payment`
- `delete_payment`
