### Retrieve a Rental Category [GET]

| Permissions   |
|---------------|
| `view_rental` |

+ Parameters
    + establishment_id (string) ... ID of the establishment
    + category_id (string) ... ID of the rental category

+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (Rental Category detailed)