### Get an Accommodation [GET /establishments/{establishment_id}/accommodations/{accommodation_id}]

| Permissions          |
|----------------------|
| `view_accommodation` |

+ Parameters
    + establishment_id (string) ... ID of the establishment
    + accommodation_id (string) ... ID of the accommodation

+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (Accommodation detailed)