# Group Accommodation

## Accommodations Collection [/establishments/{id}/accommodations]

### Retrieve all the Establishment's accommodations [GET]
| Permissions          |
|----------------------|
| `view_establishment` |
| `view_accommodation` |

+ Parameters
    + id (string) ... ID of the establishment

+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (array[Accommodation])

## Accommodation [/establishments/{id}/accommodations/{accommodation_id}]

### Retrieve all the Establishment's accommodations [GET]
| Permissions          |
|----------------------|
| `view_establishment` |
| `view_accommodation` |

+ Parameters
    + id (string) ... ID of the establishment
    + accommodation_id (string) ... ID of the accommodation

+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (Accommodation detailed)

## Accommodation Categories Collection [/establishments/{id}/accommodations/categories]

### Retrieve all the Establishment's accommodation categories [GET]
| Permissions          |
|----------------------|
| `view_establishment` |
| `view_accommodation` |

+ Parameters
    + id (string) ... ID of the establishment

+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (array[Accommodation Category])

## Accommodation Category [/establishments/{id}/accommodations/categories/{category_id}]

### Retrieve all the Establishment's accommodation categories [GET]
| Permissions          |
|----------------------|
| `view_establishment` |
| `view_accommodation` |

+ Parameters
    + id (string) ... ID of the establishment
    + category_id (string) ... ID of the accommodation category

+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (Accommodation Category detailed)

## Data Structures

### Accommodation
+ id: 1 (number, required)
+ name: Demo accommodation (string, required)
+ description: Lorem ipsum (string, optional)
+ updatedAt: `2019-11-10T12:54:45.000Z` (string, required)

### Accommodation detailed (Accommodation)
+ characteristics (array[Characteristic])
+ services (array[enum[string]])
    + Members
        + `wifi`
        + `dryer`
        + `coffee_machine`
        + `swimming_pool`
        + `elevator`
        + `television`
        + `bath`

### Characteristic
+ type (enum[string])
    + Members
        + `people`
        + `chambers`
        + `single_beds`
        + `double_beds`
        + `bathrooms`
        + `square_meters`
+ value: 4 (string)

### Accommodation Category
+ id: 1 (number, required)
+ name: Demo accommodation category (string, required)
+ description: Lorem ipsum (string, optional)

### Accommodation Category detailed (Accommodation Category)
+ accommodations (array[Accommodation])