# Group Accommodation Category

## Accommodation Categories Collection [/establishments/{establishment_id}/accommodations/categories]

{{partial "routes/index.apib"}}


## Accommodation Category [/establishments/{establishment_id}/accommodations/categories/{category_id}]

{{partial "routes/get.apib"}}


{{partial "Data.apib"}}