## Data Structures

### Accommodation Category
+ id: 1 (number, required)
+ name: Demo accommodation category (string, required)
+ description: Lorem ipsum (string, optional)

### Accommodation Category detailed (Accommodation Category)
+ accommodations (array[Accommodation])