# Group Establishments

## Establishments [/establishments]

### List All Establishments [GET]
+ Request
    + Headers

            Authorization: Bearer my-authorization-token
+ Response 200 (application/json)
    + Attributes (array[Establishment])

## Establishment [/establishments/{id}]

### Get An Establishment [GET]
+ Request
    + Headers

            Authorization: Bearer my-authorization-token
+ Response 200 (application/json)
    + Attributes (Establishment detailed)

## Data Structures

### Establishment
+ id: 1 (number, required)
+ name: Demo establishment (string, required)
+ slug: demo-establishment (string, required)
+ address: 777 Brockton Avenue (string, required)
+ complementaryAddress: Bis (string, optional)
+ zipCode: MA 2351 (string, required)
+ city: Abington (string, required)
+ country: United States (string, required)
+ updatedAt: `2019-11-10T12:54:45.000Z` (string, required)

### Establishment detailed (Establishment)
+ role
    + type: administrator
    + permissions (array)
        - view_establishment (string)
        - create_establishment (string)
        - edit_establishment (string)
        - delete_establishment (string)
        - view_establishment_token (string)
        - create_establishment_token (string)
        - edit_establishment_token (string)
        - delete_establishment_token (string)
        - view_accommodation (string)
        - create_accommodation (string)
        - edit_accommodation (string)
        - delete_accommodation (string)
        - view_rental (string)
        - create_rental (string)
        - edit_rental (string)
        - delete_rental (string)
        - view_client (string)
        - create_client (string)
        - edit_client (string)
        - delete_client (string)
        - view_booking (string)
        - create_booking (string)
        - edit_booking (string)
        - delete_booking (string)
        - view_payment (string)
        - create_payment (string)
        - edit_payment (string)
        - delete_payment (string)
