# Group Establishment

## Establishments Collection [/establishments]

### Retrieve all Establishments [GET]
+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (array[Establishment])

## Establishment [/establishments/{id}]

### Retrieve An Establishment [GET]
| Permissions          |
|----------------------|
| `view_establishment` |

+ Parameters
    + id (string) ... ID of the establishment

+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (Establishment detailed)

## Data Structures

### Establishment
+ id: 1 (number, required)
+ name: Demo establishment (string, required)
+ slug: demo-establishment (string, required)
+ address: 777 Brockton Avenue (string, required)
+ complementaryAddress: Bis (string, optional)
+ zipCode: MA 2351 (string, required)
+ city: Abington (string, required)
+ country: United States (string, required)
+ updatedAt: `2019-11-10T12:54:45.000Z` (string, required)

### Establishment detailed (Establishment)
+ role
    + type (enum[string])
        + Members
            + `administrator`
            + `manager`
            + `roles`
    + permissions (array[enum[string]])
        + Members
            + `view_establishment`
            + `create_establishment`
            + `edit_establishment`
            + `delete_establishment`
            + `view_establishment_token`
            + `create_establishment_token`
            + `edit_establishment_token`
            + `delete_establishment_token`
            + `view_accommodation`
            + `create_accommodation`
            + `edit_accommodation`
            + `delete_accommodation`
            + `view_rental`
            + `create_rental`
            + `edit_rental`
            + `delete_rental`
            + `view_client`
            + `create_client`
            + `edit_client`
            + `delete_client`
            + `view_booking`
            + `create_booking`
            + `edit_booking`
            + `delete_booking`
            + `view_payment`
            + `create_payment`
            + `edit_payment`
            + `delete_payment`
