# Group Accommodation

## Accommodations Collection [/establishments/{establishment_id}/accommodations]

{{partial "routes/index.apib"}}


## Accommodation [/establishments/{establishment_id}/accommodations/{accommodation_id}]

{{partial "routes/get.apib"}}


{{partial "Data.apib"}}