### Delete an Establishment Token [DELETE]

| Permissions                  |
|------------------------------|
| `delete_establishment_token` |

+ Parameters
    + establishment_id (string) ... ID of the establishment
    + token_id (string) ... ID of the establishment token

+ Request (application/json)
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 204