### Regenerate an Establishment Token [PATCH]

| Permissions                |
|----------------------------|
| `edit_establishment_token` |

+ Parameters
    + establishment_id (string) ... ID of the establishment
    + token_id (string) ... ID of the establishment token

+ Request (application/json)
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (Establishment Token)