### Retrieve an Accommodation Category [GET]

| Permissions          |
|----------------------|
| `view_accommodation` |

+ Parameters
    + establishment_id (string) ... ID of the establishment
    + category_id (string) ... ID of the accommodation category

+ Request
    + Headers

            Authorization: Bearer my-authorization-token

+ Response 200 (application/json)
    + Attributes (Accommodation Category detailed)