# Group Rental Category


## Rental Categories Collection [/establishments/{establishment_id}/rentals/categories]

{{partial "routes/index.apib"}}


## Rental Category [/establishments/{establishment_id}/rentals/categories/{category_id}]

{{partial "routes/get.apib"}}


{{partial "Data.apib"}}
