# Group Authentication

## Authentication [/auth]

{{partial "routes/signIn.apib"}}
{{partial "routes/logout.apib"}}
{{partial "routes/verify.apib"}}
{{partial "routes/forgotPassword.apib"}}
{{partial "routes/resetPassword.apib"}}
