# Group Establishment Token

## Establishment Tokens Collection [/establishments/{establishment_id}]

{{partial "routes/index.apib"}}
{{partial "routes/create.apib"}}


## Establishment Token [/establishments/{establishment_id}/tokens/{token_id}]

{{partial "routes/get.apib"}}
{{partial "routes/update.apib"}}
{{partial "routes/regenerate.apib"}}
{{partial "routes/delete.apib"}}

{{partial "Data.apib"}}
