## Data Structures

### Rental
+ id: 1 (number, required)
+ name: Demo rental (string, required)
+ description: Lorem ipsum (string, optional)
+ updatedAt: `2019-11-10T12:54:45.000Z` (string, required)