# Group Rental

## Rentals Collection [/establishments/{establishment_id}/rentals]

{{partial "routes/index.apib"}}


## Rental [/establishments/{establishment_id}/rentals/{rental_id}]

{{partial "routes/get.apib"}}


{{partial "Data.apib"}}
