### Reset Password [POST /auth/forgot-password]

+ Attributes
    + token (string, required) - The token received by mail
    + password: password (string, required) - The user's new password
    + passwordConfirmation: password (string, required) - Confirmation of the user's new password

+ Request (application/json)

+ Response 204