### Sign In [POST /auth/sign-in]

+ Attributes
    + uid: admin@vulpee.com (string, required)
    + password: password (string, required)

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes
        + token (string)