# Group Establishment

## Establishments Collection [/establishments]

{{partial "routes/index.apib"}}

## Establishment [/establishments/{establishment_id}]

{{partial "routes/get.apib"}}

{{partial "Data.apib"}}




