FORMAT: 1A

# Vulpee

{{partial "Authorization.apib"}}

{{partial "authentication/Authentication.apib"}}
{{partial "user/User.apib"}}

{{partial "establishment/Establishment.apib"}}
{{partial "establishmentToken/EstablishmentToken.apib"}}

{{partial "accommodation/Accommodation.apib"}}
{{partial "accommodationCategory/AccommodationCategory.apib"}}

{{partial "rental/Rental.apib"}}
{{partial "rentalCategory/RentalCategory.apib"}}